version: '3.6'
services:
  bmr_calculator:
    image: bmr_calculator:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: "Australia/Brisbane"
    ports:
      - "8051:8051" # dash
    working_dir: /app
    entrypoint: ["gunicorn", "-w", "4", "-b", "0.0.0.0:8051", "app:server"]
  